version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - store_artifacts:
        path: /home/circleci/project/server
        destination: artifacts
      - checkout # check out the code in the project directory
      - run: 
          name: update-npm-server
          command: "cd server; npm install"
      - run:
          name: test-server
          command: "cd server; npm run test"
