version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:10.15.0 # the primary container, where your job's commands are run
    steps:
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@6.4.1'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "./server/package.json" }}
      - run:
          name: install-npm-server
          command: cd server; npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "./server/package.json" }}
          paths:
            - ./server/node_modules
      - run: # run tests
          name: test-server
          command: cd server; npm run test
      - run:
          name: lint-server
          command: cd server; npm run lint
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "./client/package.json" }}
      - run:
          name: install-npm-client
          command: cd client; npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "./client/package.json" }}
          paths:
            - ./server/node_modules
      - run:
          name: build-client
          command: cd client; ng build
      - run:
          name: lint-client
          command: cd client; npm run lint
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples