export default {
        Server: Symbol("Server"),
        Socket: Symbol("Socket"),
        Application: Symbol("Application"),
        Routes: Symbol("Routes"),
        UsernameValidatorService: Symbol("UsernameValidatorService"),
        UsernameValidatorController: Symbol("UsernameValidatorController"),
        GetGameListService: Symbol("GetGameListService"),
        GetGameListController: Symbol("GetGameListController"),
        DifferenceImageGenerator: Symbol("DifferenceImageGenerator"),
        DifferenceImageController: Symbol("DifferenceImageController"),
        GameSheetGenerationController: Symbol("GameSheetGenerationController"),
        DifferencesFinderService: Symbol("DifferenceFinderService"),
        DBConnectionService: Symbol("DBConnectionService"),
        GameSheetGenerationService: Symbol("GameSheetGenerationService"),
        GetGameService: Symbol("GetGameService"),
        GetGameController: Symbol("GetGameService"),
        SceneDataGeneratorService: Symbol("SceneDataGeneratorService"),
        SceneDataControler: Symbol("SceneDataControler"),
        SceneDataDifferenceService: Symbol("SceneDataDifferenceService"),
        DifferenceCheckerService: Symbol("DifferenceCheckerService"),
        DifferenceCheckerController: Symbol("DifferenceCheckerController"),
};
